  MEMBER('CML_Data_ManyToManyLinkTests.clw')


  MAP
CML_Data_ManyToManyLinkTests_BC0:DctInit    PROCEDURE
CML_Data_ManyToManyLinkTests_BC0:DctKill    PROCEDURE
CML_Data_ManyToManyLinkTests_BC0:FilesInit  PROCEDURE
  END




CML_Data_ManyToManyLinkTests_BC0:DctInit PROCEDURE
  CODE


CML_Data_ManyToManyLinkTests_BC0:FilesInit PROCEDURE
  CODE


CML_Data_ManyToManyLinkTests_BC0:DctKill PROCEDURE
  CODE

